## Manifiesto de despliegie
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-demo
  labels:
    app: ping-demo
spec:
  replicas: 6
  selector:
    matchLabels:
      app: ping-demo
  template:
    metadata:
      labels:
        app: ping-demo
    spec:
      containers:
<<<<<<< Updated upstream
        - name: "demoping"
          image: "116933114869.dkr.ecr.us-east-1.amazonaws.com/demoping"
          imagePullPolicy: IfNotPresent
=======
        - name: ping-demo-app
          image: 116933114869.dkr.ecr.us-east-1.amazonaws.com
>>>>>>> Stashed changes
          ports:
            - containerPort: 80
              protocol: TCP
