apiVersion: apps/v1
king: Deployment
metadata:
  name: ping-demo
  labels:
    app: ping-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ping-demo
  template:
    metadata:
      labels:
        app: ping-demo
    spec:
      containers:
        - name: ping-demo-app
          image: ping-demo:a81b70d
          ports:
            - containerPort: 20400
