apiVersion: v1
kind: Service
metadata:
  name: ping-demo-service
  labels:
    app: ping-demo
spec:
  selector:
    app: ping-demo
  ports:
    - name: http
      protocol: TCP
      port: 30400
      nodePort: 30400
      targetPort: 30400
    - name: https
      protocol: TCP
      port: 32400
      nodePort: 32400
      targetPort: 32400
  type: NodePort
  env:
    - name: identificador
      value: /home/runner/work/_temp/_runner_file_commands/set_env_e66b7a24-af31-4206-a9e7-9c4462416c9d



