apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-demo
  labels:
    app: ping-demo
spec:
  replicas: 6
  selector:
    matchLabels:
      app: ping-demo
  template:
    metadata:
      labels:
        app: ping-demo
    spec:
      containers:
        - name: "demoping"
          image: "https://116933114869.dkr.ecr.us-east-1.amazonaws.com/demoping"
          ports:
            - containerPort: 80
