apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-demo
  labels:
    app: ping-demo
spec:
  replicas: 6
  selector:
    matchLabels:
      app: ping-demo
  template:
    metadata:
      labels:
        app: ping-demo
    spec:
      containers:
        - name: demopingpub
          image: public.ecr.aws/z4u0p9o7/argocd/demopingpub
          ports:
            - containerPort: 20400
