apiVersion: v1
kind: Service
metadata:
  name: ping-demo-service
  labels:
    app: ping-demo
spec:
  selector:
    app: ping-demo
  ports:
    - protocol: TCP
      port: 30400
      targetPort: 30400
  type: NodePort



